package:
  name: flask-peewee
  version: "0.6.7"

source:
  fn: flask-peewee-0.6.7.tar.gz
  url: https://pypi.python.org/packages/ab/3d/cc8c9c0b981eeb8f7356847512757d430e5c95a690673f0eb2b9fa2405e4/flask-peewee-0.6.7.tar.gz
  md5: 2d94387bdd1a7596c4667fb5588190fe
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-peewee = flask-peewee:main
    #
    # Would create an entry point called flask-peewee that calls flask-peewee.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask
    - werkzeug
    - jinja2
    - peewee >=2.7.3
    - wtforms
    - wtf-peewee

  run:
    - python
    - flask
    - werkzeug
    - jinja2
    - peewee >=2.7.3
    - wtforms
    - wtf-peewee

test:
  # Python imports
  imports:
    - example
    - flask_peewee
    - flask_peewee.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/coleifer/flask-peewee/
  license: BSD License
  summary: 'Peewee integration for flask'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
