package:
  name: flask-debugtoolbar
  version: "0.10.1"

source:
  fn: Flask-DebugToolbar-0.10.1.tar.gz
  url: https://pypi.python.org/packages/ce/5e/bfbfcebfcc25ffe4a5c8ee03b073b3e87e2890d69ddb45a32f1bf72615d0/Flask-DebugToolbar-0.10.1.tar.gz
  md5: b68ab1253ad368fa676e34256882d8ff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-debugtoolbar = flask-debugtoolbar:main
    #
    # Would create an entry point called flask-debugtoolbar that calls flask-debugtoolbar.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask >=0.8
    - blinker
    - itsdangerous
    - werkzeug

  run:
    - python
    - flask >=0.8
    - blinker
    - itsdangerous
    - werkzeug

test:
  # Python imports
  imports:
    - flask_debugtoolbar
    - flask_debugtoolbar.panels

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://flask-debugtoolbar.readthedocs.io/
  license: BSD License
  summary: 'A toolbar overlay for debugging Flask applications.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
