package:
    name: flask-mongoengine
    version: "0.9.2"

source:
    fn: flask-mongoengine-0.9.2.tar.gz
    url: https://pypi.python.org/packages/e8/59/0b48d9564436d89f6097bdb64ae75db1cd83801a960c3c44a90926d38735/flask-mongoengine-0.9.2.tar.gz
    md5: d52285c814dee0db172a79bcb76d71fc
#    patches:
     # List any patch files here
     # - fix.patch

# build:
    # noarch_python: True
    # preserve_egg_dir: True
    # entry_points:
        # Put any entry points (scripts to be generated automatically) here. The
        # syntax is module:function.    For example
        #
        # - flask-mongoengine = flask-mongoengine:main
        #
        # Would create an entry point called flask-mongoengine that calls flask-mongoengine.main()


    # If this is a new build for the same version, increment the build
    # number. If you do not include this key, it defaults to 0.
    # number: 1

requirements:
    build:
        - python
        - setuptools
        - flask >=0.8
        - flask-wtf >=0.13
        - mongoengine >=0.8.0
        - six
        - rednose
        - nose
        - coverage

    run:
        - python
        - flask >=0.8
        - flask-wtf >=0.13
        - mongoengine >=0.8.0
        - six
        # - rednose
        # - nose
        # - coverage

test:
    # Python imports
    imports:
        - flask_mongoengine
        - flask_mongoengine.wtf

    # commands:
        # You can put test commands to be run here.    Use this to test that the
        # entry points work.


    # You can also put a file called run_test.py in the recipe that will be run
    # at test time.

    requires:
        - rednose
        - nose
        - coverage
        - six
        # Put any additional test requirements here.    For example
        # - nose

about:
    home: https://github.com/mongoengine/flask-mongoengine
    license: BSD License
    summary: 'Flask-MongoEngine is a Flask extension that provides integration with MongoEngine and WTF model forms.'
    license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
