package:
  name: mr.bob
  version: "0.1.2"

source:
  fn: mr.bob-0.1.2.tar.gz
  url: https://pypi.python.org/packages/23/fe/25d78b8e9c84ac177fc3edae0186b842d0a788f19710c250b08a23fdb528/mr.bob-0.1.2.tar.gz
  md5: 4856a2c9677894931a9f5bd1bf388dab
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mr.bob = mr.bob:main
    #
    # Would create an entry point called mr.bob that calls mr.bob.main()

    - mrbob=mrbob.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - setuptools
    - six >=1.2.0
    - jinja2 >=2.5.0

  run:
    - python
    - setuptools
    - setuptools
    - six >=1.2.0
    - jinja2 >=2.5.0

test:
  # Python imports
  imports:
    - mrbob
    - mrbob.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - mrbob --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/iElectric/mr.bob.git
  license: BSD
  summary: 'Bob renders directory structure templates'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
