package:
  name: progressbar2
  version: "3.6.2"

source:
  fn: progressbar2-3.6.2.tar.gz
  url: https://pypi.python.org/packages/source/p/progressbar2/progressbar2-3.6.2.tar.gz
  md5: 8eb9815013f48f824a0e57da0add74ab
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - progressbar2 = progressbar2:main
    #
    # Would create an entry point called progressbar2 that calls progressbar2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argparse

  run:
    - python
    - argparse

test:
  # Python imports
  imports:
    - progressbar

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/WoLpH/python-progressbar
  license: BSD License
  summary: 'A Python Progressbar library to provide visual (yet text based) progress to\nlong running operations.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
