package:
  name: pytzdata
  version: "2016.10"

source:
  fn: pytzdata-2016.10.tar.gz
  url: https://pypi.python.org/packages/d8/42/dfddc0e6f6998aea2053b9c16ccf341b339929399ed6a0000042839b02e3/pytzdata-2016.10.tar.gz
  md5: c8ba88b930efe12ae40e614b635f24a1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytzdata = pytzdata:main
    #
    # Would create an entry point called pytzdata that calls pytzdata.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pytzdata
    - pytzdata.commands

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/sdispater/pytzdata
  license: MIT
  summary: 'Official timezone database for Python.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
