package:
  name: flask-celery-helper
  version: "1.1.0"

source:
  fn: Flask-Celery-Helper-1.1.0.tar.gz
  url: https://pypi.python.org/packages/71/f5/3631b71ac28d9b691ff2e2371a95121be18c742c963098635c11cf4a254f/Flask-Celery-Helper-1.1.0.tar.gz
  md5: 1850fa43dff0c909cbde348e83be5bed
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-celery-helper = flask-celery-helper:main
    #
    # Would create an entry point called flask-celery-helper that calls flask-celery-helper.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask
    - celery

  run:
    - python
    - flask
    - celery

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Robpol86/Flask-Celery-Helper
  license: MIT License
  summary: 'Celery support for Flask without breaking PyCharm inspections.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
