package:
  name: flask-diamond
  version: "0.5.1"

source:
  fn: Flask-Diamond-0.5.1.tar.gz
  url: https://pypi.python.org/packages/4a/17/0e63dfe473fb77aaf6992a16783c51016c24333310574c4a2e3a26b7028d/Flask-Diamond-0.5.1.tar.gz
  md5: a692ada9482d83995c0bb6c7c8076bc5
  patches:
    # List any patch files here
    - requirements.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-diamond = flask-diamond:main
    #
    # Would create an entry point called flask-diamond that calls flask-diamond.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - flask >=0.11.1
    - flask-migrate >=1.3.0
    - flask-admin >=1.1.0
    - flask-wtf >=0.13.1
    - flask-login >=0.3.2
    - flask-security >=1.7.5
    - flask-script >=2.0.5
    - flask-mail >=0.9.1
    - flask-testing >=0.4.2
    - flask-debugtoolbar >=0.9.2
    - flask-assets >=0.10
    # - flask-dbshell >=1.0
    - flask-restful >=0.3.2
    - flask-markdown >=0.3
    - flask-sqlalchemy >=2.0
    - flask-marshmallow >=0.5.0
    - flask-celery-helper >=1.1.0
    - werkzeug >=0.11.11
    - jinja2 >=2.8
    - sphinx >=1.2.3
    - fabric3 >=1.10.2
    - nose >=1.3.4
    - watchdog >=0.8.3
    - wheel >=0.24.0
    - pylint >=1.4.1
    - mr.bob >=0.1.1
    - marshmallow >=1.2.6
    - alembic >=0.7.4
    - gunicorn >=19.3.0
    - gitpython >=1.0.1
    - wtforms >=1.0.5
    - alabaster >=0.7.7
    - future >=0.16
    - click >=6.6

  run:
    - python
    - flask >=0.11.1
    - flask-migrate >=1.3.0
    - flask-admin >=1.1.0
    - flask-wtf >=0.13.1
    - flask-login >=0.3.2
    - flask-security >=1.7.5
    - flask-script >=2.0.5
    - flask-mail >=0.9.1
    - flask-testing >=0.4.2
    - flask-debugtoolbar >=0.9.2
    - flask-assets >=0.10
    # - flask-dbshell >=1.0
    - flask-restful >=0.3.2
    - flask-markdown >=0.3
    - flask-sqlalchemy >=2.0
    - flask-marshmallow >=0.5.0
    - flask-celery-helper >=1.1.0
    - werkzeug >=0.11.11
    - jinja2 >=2.8
    - sphinx >=1.2.3
    - fabric3 >=1.10.2
    - nose >=1.3.4
    - watchdog >=0.8.3
    - wheel >=0.24.0
    - pylint >=1.4.1
    - mr.bob >=0.1.1
    - marshmallow >=1.2.6
    - alembic >=0.7.4
    - gunicorn >=19.3.0
    - gitpython >=1.0.1
    - wtforms >=1.0.5
    - alabaster >=0.7.7
    - future >=0.16
    - click >=6.6

test:
  # Python imports
  imports:
    - flask_diamond
    - flask_diamond.facets
    - flask_diamond.mixins
    - flask_diamond.models
    - flask_diamond.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://flask-diamond.readthedocs.org
  license: MIT License
  summary: 'Flask-Diamond provides some opinions about data-centric Internet applications and systems. Flask-Diamond is a batteries-included Flask framework, sortof like Django but radically decomposable.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
