package:
  name: wtforms
  version: "2.1"

source:
  fn: WTForms-2.1.zip
  url: https://pypi.python.org/packages/bf/91/2e553b86c55e9cf2f33265de50e052441fb753af46f5f20477fe9c61280e/WTForms-2.1.zip
  md5: 6938a541fafd1a1ae2f6b9b88588eef2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wtforms = wtforms:main
    #
    # Would create an entry point called wtforms that calls wtforms.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - wtforms
    - wtforms.csrf
    - wtforms.ext
    - wtforms.ext.appengine
    - wtforms.ext.csrf
    - wtforms.ext.dateutil
    - wtforms.ext.django
    - wtforms.ext.django.templatetags
    - wtforms.ext.i18n
    - wtforms.ext.sqlalchemy
    - wtforms.fields
    - wtforms.widgets

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://wtforms.simplecodes.com/
  license: BSD License
  summary: 'A flexible forms validation and rendering library for python web development.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
